name: CI/CD - Projeto Básico

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar e rodar ESLint (opcional)
      run: |
        npm install eslint --save-dev
        npx eslint script.js || echo "Lint finalizado com alertas."

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Deploy no GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # pasta raiz, pois seus arquivos estão no root
